# Generated by Django 4.1 on 2024-02-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Description')),
                ('price', models.CharField(max_length=255, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, serialize=False, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('created_at',),
            },
        ),
    ]
