# Generated by Django 4.1 on 2024-02-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_anotherservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherservices',
            name='service_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='base.service'),
        ),
    ]
