# Generated by Django 4.1 on 2024-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_anotherservices_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotherservices',
            name='service_id',
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='title_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
