# Generated by Django 4.1 on 2024-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_anotherservices_service_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_description', models.TextField()),
                ('price', models.CharField(max_length=255)),
                ('tax', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Family Service',
                'verbose_name_plural': 'Family Services',
            },
        ),
    ]
