# Generated by Django 4.1 on 2024-02-26 08:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_familyservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherservices',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='familyservices',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
