# Generated by Django 4.1 on 2024-02-26 08:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_anotherservices_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherservices',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='familyservices',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
