# Generated by Django 4.1 on 2024-02-28 06:06

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_anotherservices_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotherservices',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RemoveField(
            model_name='anotherservices',
            name='title',
        ),
        migrations.RemoveField(
            model_name='anotherservices',
            name='title_description',
        ),
        migrations.RemoveField(
            model_name='familyservices',
            name='description',
        ),
        migrations.RemoveField(
            model_name='familyservices',
            name='title',
        ),
        migrations.RemoveField(
            model_name='familyservices',
            name='title_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='description_ru',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='title_description_en',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Title description in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='title_description_ru',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Title description in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='title_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='title_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='description_en',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Description in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='description_ru',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Description description in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='title_description_en',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Title description in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='title_description_ru',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Title description in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='title_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='title_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Description in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Description in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title in Russian'),
            preserve_default=False,
        ),
    ]
