# Generated by Django 4.1 on 2024-02-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_description_anotherservices_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotherservices',
            name='price',
        ),
        migrations.RemoveField(
            model_name='anotherservices',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='familyservices',
            name='price',
        ),
        migrations.RemoveField(
            model_name='familyservices',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='price_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Price in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='price_ru',
            field=models.CharField(default=11, max_length=255, verbose_name='Price in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='tax_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Tax in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotherservices',
            name='tax_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Tax in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='price_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Price in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='price_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Price in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='tax_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Tax in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='tax_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Tax in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Price in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Price in Russian'),
            preserve_default=False,
        ),
    ]
