# Generated by Django 4.1 on 2024-03-20 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_service_options_anotherservices_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherservices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, serialize=False, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyservices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, serialize=False, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
