# Generated by Django 4.1 on 2024-03-20 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_anotherservices_created_at_familyservices_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text_en',
            field=ckeditor.fields.RichTextField(verbose_name='Description in English'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text_ru',
            field=ckeditor.fields.RichTextField(verbose_name='Description description in Russian'),
        ),
    ]
